name: Test Bun App with Nginx and Local DNS

on:
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-nginx-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          bun install
          pip install requests aiohttp brotli

      - name: Install Debian Chromium & Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg xvfb software-properties-common
          sudo add-apt-repository -y ppa:xtradeb/apps
          sudo apt-get update
          sudo apt-get install -y chromium xvfb
          
      - name: yayaya ini dia
        run: |
          xvfb-run --server-args="-screen 0 1280x1024x24" bun main.ts &
          sleep 5
          cd sc
          timeout 240m python popaja.py || true

      - name: Commit & Push
        run: |
          git config user.name "callmehuda"
          git config user.email "mafatikhul.huda118@smk.belajar.id"
          echo "Last run: $(date '+%Y-%m-%d %H:%M:%S')" > last_run.txt
          git add last_run.txt
          git diff --staged --quiet || git commit -m "chore: update last run $(date '+%Y-%m-%d %H:%M')"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git main
